version: '3'

services:

  esl-service:
    build:
      context: ./../esl-service
      dockerfile: ./../esl-service/esl-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mssql-service:
    env_file:
      - path: ./../mssql-service/.env
    build:
      context: ./../mssql-service
      dockerfile: ./../mssql-service/mssql-service.dockerfile
    ports:
      - 8081:8080
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    