version: '3'

services:

  esl-service:
    env_file: "./../esl-service/.env"
    build:
      context: ./../esl-service
      dockerfile: ./../esl-service/esl-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mssql-service:
    env_file:
      - path: ./../mssql-service/.env
    build:
      context: ./../mssql-service
      dockerfile: ./../mssql-service/mssql-service.dockerfile
    ports:
      - 8091:8080
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  redis:
    image: redis:7.2.5-alpine
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    restart: always
    ports:
      - 8092:6379
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=${password}
    volumes:
      - ./../redis-data:/data
    command: redis-server --requirepass ${password}
